#!/bin/bash


#if [[ $1 -eq "test" ]]; then
	#echo "Testing config"
	#sudo python inputs.py config.json

	
sudo python inputs.py config.json
#sudo python inputs.py 
#sudo python $BIN_DIR/THING/inputs.py $CONF_DIR/THING/config.json
